### ISSUE TITLE
Dev tooling?

### ISSUE THREAD

**Issue by ThreeScreenStudios** [mobxjs/mobx-vue#7]
Thank you for all your work with Mobx-vue and helping make Mobx work with Vue! I've just started working with MobX + Vue and liking it a lot so far. 

One question I had was about any dev tooling available that is stack agnostic or Vue specific, as it looks like the Mobx chrome dev tools and Delorean for time travel debugging is Mobx + React only? If there isn't any at the moment, are there plans for this in the future?

**Comment by kuitos** [comment]
It's great that this lib is helpful for you!

Mobx dev tool should be a universal stuff rather than a special one such as a mobx-vue-tool or mobx-react-tool imo.

After googling I found this project: https://github.com/zalmoxisus/mobx-remotedev, seems suit for all mobx project, hope helpful for you.

Feel free to ask any question😀.

**Comment by ThreeScreenStudios** [comment]
Great, will check mobx-remotedev out, thank you!

**Comment by teleclimber** [comment]
Sadly mobx-remotedev seems abandoned. Trying to install it NPM gave me a security warning (no biggie, but it's not a good sign). There are a number of branches though, did anybody find a good one that works with mobx 5?
